version: "3.8"

services:

  flask:
    build: ./flask
    container_name: flask-app
    restart: always
    # command: python3 app.py
    ports:
      - 8080:8080
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"